// Code generated by "go-ioc"; DO NOT EDIT.
package dependent

import (
	"github.com/catmorte/go-ioc/examples/pkg/independent"
	goIoc0 "github.com/catmorte/go-ioc/pkg/context"
)

func init() {
	dep0_0 := goIoc0.DepScoped[*independent.IndependentObj1]("independentScope1")
	dep0_1 := goIoc0.DepScoped[independent.IndependentObj2]("independentScope2")
	goIoc0.RegPrototype(func() *DependentObj {
		v := &DependentObj{
			IndependentObj1: goIoc0.ResolveDep[*independent.IndependentObj1](dep0_0),
			IndependentObj2: goIoc0.ResolveDep[independent.IndependentObj2](dep0_1),
		}
		v.Init()
		return v
	}, dep0_0, dep0_1)

}
